replicaCount: 1

image:
  repository: nim-factory-poc-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

config:
  minimumTpsThreshold: "100"
  nimBaseUrl: "https://integrate.api.nvidia.com/v1"
  nimTimeoutSeconds: "30"

secret:
  create: false
  name: nim-factory-secrets
  nvidiaApiKey: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8000"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
