apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nim-factory.fullname" . }}-config
  labels:
    {{- include "nim-factory.labels" . | nindent 4 }}
data:
  NIM_MINIMUM_TPS_THRESHOLD: {{ .Values.config.minimumTpsThreshold | quote }}
  NIM_BASE_URL: {{ .Values.config.nimBaseUrl | quote }}
  NIM_TIMEOUT_SECONDS: {{ .Values.config.nimTimeoutSeconds | quote }}
