apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-gpu-benchmarking.fullname" . }}-worker
  labels:
    {{- include "llm-gpu-benchmarking.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "llm-gpu-benchmarking.workerSelectorLabels" . | nindent 4 }}
